// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu_iz8DEuaClcdBoGBAxhQHno7t2IKqKg',
    appId: '1:772264666192:web:25869930c50db8b139dd55',
    messagingSenderId: '772264666192',
    projectId: 'mynotes-demo-flutter-7a309',
    authDomain: 'mynotes-demo-flutter-7a309.firebaseapp.com',
    storageBucket: 'mynotes-demo-flutter-7a309.appspot.com',
    measurementId: 'G-3K13HQ46WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp445PJb30tLUuYDDSGPvL1naQyALgDL0',
    appId: '1:772264666192:android:864a92f5f074abd139dd55',
    messagingSenderId: '772264666192',
    projectId: 'mynotes-demo-flutter-7a309',
    storageBucket: 'mynotes-demo-flutter-7a309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpM4Oa-6ya7iPbRqLhg1jHhmElsy8_yts',
    appId: '1:772264666192:ios:c5c2bd6f3a4f95c839dd55',
    messagingSenderId: '772264666192',
    projectId: 'mynotes-demo-flutter-7a309',
    storageBucket: 'mynotes-demo-flutter-7a309.appspot.com',
    iosClientId: '772264666192-9j5b582r4kvuqpc59o8tvu8cq00qt9f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpM4Oa-6ya7iPbRqLhg1jHhmElsy8_yts',
    appId: '1:772264666192:ios:c5c2bd6f3a4f95c839dd55',
    messagingSenderId: '772264666192',
    projectId: 'mynotes-demo-flutter-7a309',
    storageBucket: 'mynotes-demo-flutter-7a309.appspot.com',
    iosClientId: '772264666192-9j5b582r4kvuqpc59o8tvu8cq00qt9f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
